
#user  nobody;
# multiple workers works !
worker_processes  1;

#error_log  logserror.log;
#error_log  logserror.log  notice;
#error_log  logserror.log  info;

#pid        logsnginx.pid;


events {
    worker_connections  1024;
    # max value 32768, nginx recycling connections+registry optimization = 
    #   this.value  20 = max concurrent connections currently tested with one worker
    #   C1000K should be possible depending there is enough ramcpu power
    # multi_accept on;
}


			#exec_push Cffmpegbinffmpeg.exe -re -i rtmp127.0.0.1live$name -cv libx264 -preset veryfast -bv 2500k -maxrate 2500k -bufsize 5000k -ca aac -ba 128k -f flv rtmpdus01.contribute.live-video.netapplive_103730834_oDulJIscNiy6831O92eHBVgk93AaES;


rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application live1 {
            live on;
            record off;
            hls off;
            dash off;
            wait_key on;

            # احراز هویت و شروع استریم برای live1
            on_publish        http://127.0.0.1:8000/auth?server=live1;
            # پایان استریم یا قطع ارسال
            on_publish_done   http://127.0.0.1:8000/stop?name=$name;

            push rtmp://live.restream.io/live/Streamkey;
            # push rtmp://a.rtmp.youtube.com/live2/Streamkey;
            # push rtmp://dus01.contribute.live-video.net/app/Streamkey;

            # برای استفاده از FFMPEG از SAAMA استفاده کنید.
        }

        application live2 {
            live on;
            record off;
            hls off;
            dash off;
            wait_key on;

            # احراز هویت و شروع استریم برای live2
            on_publish        http://127.0.0.1:8000/auth?server=live2;
            # پایان استریم یا قطع ارسال
            on_publish_done   http://127.0.0.1:8000/stop?name=$name;

            # push rtmp://a.rtmp.youtube.com/live2/Streamkey;
            # push rtmp://dus01.contribute.live-video.net/app/Streamkey;

            # برای استفاده از FFMPEG از SAAMA استفاده کنید.
        }
    }
}
