
#user  nobody;
# multiple workers works !
worker_processes  2;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  8192;
    # max value 32768, nginx recycling connections+registry optimization = 
    #   this.value * 20 = max concurrent connections currently tested with one worker
    #   C1000K should be possible depending there is enough ram/cpu power
    # multi_accept on;
}



rtmp {
    server {
        listen 1935;  # سرور اول
        chunk_size 4096;

        application live1 {
            live on;
            record off;
            on_publish http://127.0.0.1:8000/auth?server=live1;
            push rtmp://rtmp.cdn.asset.aparat.com:443/event/live1key;
            push rtmp://b.rtmp.youtube.com/live2/yyyy-yyyy-yyyy-yyyy;
        }

        application live2 {
            live on;
            record off;
            on_publish http://127.0.0.1:8000/auth?server=live2;
            push rtmp://rtmp.cdn.asset.aparat.com:443/event/live2key;
            push rtmp://b.rtmp.youtube.com/live2/yyyy-yyyy-yyyy-yyyy;
        }

        application live3 {
            live on;
            record off;
            on_publish http://127.0.0.1:8000/auth?server=live3;
            push rtmp://rtmp.cdn.asset.aparat.com:443/event/live3key;
            push rtmp://c.rtmp.youtube.com/live2/zzzz-zzzz-zzzz-zzzz;
        }
    }
}
